- pycarol/carolina.py
- pycarol/storage.py
> fix: get new storage token when app name changes

- pycarol/staging.py
Added the `/api/v2/staging/tables/{staging_name}/drop` endpoint to pycarol
> Drop Staging tables endpoints.

- README.rst
- pycarol/carol.py
- pycarol/cds.py
- pycarol/query.py
- pycarol/staging.py
- pycarol/storage.py
- setup.cfg
- setup.py
Fix some issues with documentation.
Added more documentation about queries and staging.
> More documentation 

- .dependabot/config.yml
This bot is already configured, we just want to ensure some details when a PR is filed.
> fix: added dependabot config

- pycarol/carol.py
- pycarol/carolina.py
- pycarol/cds.py
- pycarol/filter.py
- pycarol/query.py
- pycarol/staging.py
- pycarol/storage.py
- setup.py
1. Added more documentation for Query, Storage, Staging, Filter
2. Added the README.rst to pypi description.
> More documentation

- pycarol/cds.py
> fix variables default

- pycarol/data_models/data_model_view.py
- pycarol/data_models/data_models.py
- pycarol/staging.py
- pycarol/utils/miscellaneous.py
With 3.7 we are removing the old staging and DM exporter. I added the msgs saying the parameters will be removed.
> add deprecation msgs.

- pycarol/cds.py
we are not supporting the machines with cpu count > 16
> remove machines not supported.

- pycarol/staging.py
Request from @poffo .  Add the option to send data to the Sync API
```python 
from pycarol import Carol, Staging
carol = Carol()
records = [{"cd_modalidade":i,"cd_usuario":i+1,"nr_proposta":i+2,"aa_fim_compl":i+3,} for i in range(2300)]
Staging(carol).send_data(staging_name='usuario',  data=records, connector_name='datasul', 
carol_sync=True, print_stats=True)
```
> send data to the sync API

- pycarol/tasks.py
Related to this issue: https://github.com/totvslabs/pyCarol/issues/379
> fix: reviewing Tasks' methods

- pycarol/apps.py
> fix: return tasks when building docker images from git

- pycarol/cds.py
Many APIs have changed some parameters after 3.7. This is the update of these APIs.
> Cds update apis

- pycarol/compute.py
Add the APIs to get app execution logs. 
```python
c = Compute(Carol())
app_name = 'vscode'
filters = ['''labels."k8s-pod/kind"="build"''', f'''labels."k8s-pod/appName":"{app_name}"''']
r = c.get_app_logs(filters=filters, page_size=100)
r['logEntries']
```
> Stack Drive logs

- pycarol/data_models/data_model_view.py
- pycarol/data_models/data_models.py
- pycarol/staging.py
- pycarol/tenant.py
This is the old exporter. It is being disabled.
> Remove exporter

- pycarol/utils/storage_gcpcs.py
This if can break if using multiple threads.
> fix: temp path in Storage()

- pycarol/cds.py
> New parameter when processing CDS.

- .bumpversion.cfg
- .github/workflows/release.yml
This will automatically create a release once we tag a commit.
> feat: git action to create a release

- pycarol/connectors.py
- pycarol/data_models/data_models.py
> Add ETL and Mapping options

- examples/dynamic_task.py
- pycarol/pipeline/task/task.py
Added compatibility  with luigi's dynamic tasks. 
Added a example of using this feature too. 
https://luigi.readthedocs.io/en/stable/tasks.html#dynamic-dependencies
> dynamic dependencies

- pycarol/__init__.py
- pycarol/carol.py
Added a custom exception to handle wrong login/password.
> custom exception for passoword error.

- README.rst
- doc/source/conf.py
- doc/source/pycarol/auth.rst
- doc/source/pycarol/pipeline.rst
- doc/source/pycarol/pyCarol.rst
- pycarol/auth/ApiKeyAuth.py
- pycarol/auth/PwdAuth.py
- pycarol/auth/PwdKeyAuth.py
- setup.py
This `PwdKeyAuth` auth method is new and it was not in the documentation. 
https://github.com/totvslabs/pyCarol/issues/474
> docs: documentation for PwdKeyAuth

- pycarol/__init__.py
- pycarol/carol.py
- pycarol/data_models/data_models.py
- pycarol/exceptions.py
Validation if datamodel already exists
> Fix datamodel validation

- pycarol/data_models/data_models.py
- pycarol/staging.py
- pycarol/utils/miscellaneous.py
pandas shouldn't be required when send data through json
> fix: pandas not required

- pycarol/pipeline/tools/_tools.py
There were cases where the old dag generation was not working. Now it was fixed. 
It was overwriting some parametros when using `inherit_list`.
> bug: fix dag creation

- pycarol/__init__.py
- pycarol/carolina.py
- pycarol/data_models/data_models.py
- pycarol/storage.py
- pycarol/utils/importers.py
- pycarol/utils/storage_gcpcs.py
Allow user to fetch rejected records from data model.
We need to wait Carol deploy to be able to merge this.
> feat: fetch rejected records from cds

- Makefile
- pycarol/tenant.py
This API changed behavior when running without auth. To guarantee dont have problems I added the auth parameter as `True`
> fix: Fix tenant class.

- pycarol/apps.py
This will allow the user to:
1. update app settings
2. install/update the app
3. start app process
4. app information
> feat:add app features

- pycarol/utils/importers.py
There is a bug in carol that is not save files as gzip. This will allow us to skill fetch those files.
> bug: fetch rejected when using multiple workers. 

- examples/pipeline/pipelie_ex/a_notebook_task.ipynb
- examples/pipeline/pipelie_ex/pipeline.py
- examples/pipeline/pipelie_ex/some_tasks.py
- examples/pipeline/pipelie_ex/task_config.py
- examples/pipeline/pipeline_example.ipynb
- examples/pipeline/using_jupyter_tasks.ipynb
- pycarol/pipeline/__init__.py
- pycarol/pipeline/task/task.py
One of the most undocumented part from pycarol is the Luigi/task/pipeline APIS. I created some notebooks and a small pipeline example.
> feat: pipelines examples

- pycarol/apps.py
- pycarol/carol.py
- pycarol/utils/miscellaneous.py
Allow uploading the app artifacts. Could be the manifest.json or the site artifacts.
> feat: allow to upload app artifacts

- pycarol/__init__.py
> new dm columns

- pycarol/utils/importers.py
Carol is creating json files without the \n between json.  I had to handle on our side until a fix in carol.
> bug: hack to load json.

- pycarol/cds.py
This new parameter in golden and staging will allow us to consolidate only the records that match with the given pattern.
> feat: new parameter on consolidate.

- pycarol/__init__.py
- pycarol/subscription.py
Support for the new subscriptions
> feat-subscriptions class

- pycarol/carol.py
> retry on post

- pycarol/organization.py
> feat: org/env by id

- pycarol/organization.py
This APIs will work without authentication as well, need to allow this.
> bug: do not use auth in get_by_id

- pycarol/cds.py
This is a new param for staging consolidate.
> feat: new staging consolidate param

- pycarol/cds.py
Delete golden rejected records from CDS.
> feat: delete rejected.

- pycarol/staging.py
Improve the way we handle possible input data for send_data
> feat: improve the error handler during send_data

- pycarol/cds.py
This new parameter will force dataflow to use the number of workers set.
> feat: New parameter for processing staging

- pycarol/cds.py
> new-machiens

- pycarol/cds.py
This parameter allows us to disable auto-scaling
> feat - add auto-scaling param to CDS golden

- pycarol/carol.py
Allow the user to specify the connector to create the api key.
> feat Issue an APIkey to a connector

- pycarol/data_models/data_models.py
Add a new param when fetching datamodel info
> feat: Data Model new parameter. 

- hack/setup.sh
> fix: build

- pycarol/cds.py
Add the new param to consolidate only small files.
> feat: Add max file size to consolidate API

- pycarol/__init__.py
- pycarol/data_models/data_models.py
- pycarol/staging.py
- pycarol/utils/miscellaneous.py
We are using the wrong field to untie two records in golden CDS.
> fix: wrong field user when untie record in CDS golden.

- pycarol/apps.py
when there is no settings pycarol breaks
> bug: fix empty settings

- pycarol/cds.py
Machines types change. And we need to keep pycarol updated. I will only warn the user.
> remove machine type verification

- pycarol/carol_api.py
These two are unpickleable, and break if we try to use this within joblib/multiprocessin any tool that needs to pickel the instance.
> Remove storage/carolina

- pycarol/carol_api.py
- pycarol/connectors.py
Get the list of stagings in a connector.
> feat: Api to get all stagings

- pycarol/data_models/data_models.py
- pycarol/staging.py
APIs to generate SQL tables for staging and DMs.
> feat: Generate SQL tables for DMs and Stagings.

- doc/source/pycarol/api/pycarol.apps.rst
- doc/source/pycarol/api/pycarol.auth.rst
- doc/source/pycarol/api/pycarol.carol.rst
- doc/source/pycarol/api/pycarol.carolina.rst
- doc/source/pycarol/api/pycarol.cds.rst
- doc/source/pycarol/api/pycarol.connectors.rst
- doc/source/pycarol/api/pycarol.filter.rst
- doc/source/pycarol/api/pycarol.logger.rst
- doc/source/pycarol/api/pycarol.named_query.rst
- doc/source/pycarol/api/pycarol.query.rst
- doc/source/pycarol/api/pycarol.staging.rst
- doc/source/pycarol/api/pycarol.storage.rst
- doc/source/pycarol/api/pycarol.tasks.rst
- doc/source/pycarol/api/pycarol.tenant.rst
- doc/source/pycarol/generated/pycarol.auth.ApiKeyAuth.rst
- doc/source/pycarol/generated/pycarol.auth.PwdAuth.rst
- doc/source/pycarol/generated/pycarol.auth.PwdKeyAuth.rst
- doc/source/pycarol/generated/pycarol.auth.rst
- doc/source/pycarol/generated/pycarol.tools.dag.rst
- doc/source/pycarol/tools.rst
- pycarol/tools/__init__.py
- pycarol/tools/dag.py
This 4 functions will build the dependency graph of all stagings, datamodels.
> feat: dependency graph generator.

- pycarol/tasks.py
We are parsing some fields from the task, but not saving the raw results. This is bad since new fields can be added.
> feat: add raw task information

- pycarol/storage.py
- pycarol/utils/storage_gcpcs.py
Add params space to save in CDS.
> feat: add storage space for save CDS

- hack/release.sh
The pip search API was deprecated. need to change the way we get the version
> fix release docker hub

- hack/release.sh
> fix: make relase

- pycarol/cds.py
Add the `force_paused` parameter to CDS process staging
> feature: Process new parameter

- pycarol/utils/importers.py
- pycarol/utils/storage_gcpcs.py
carol is not using gzip anymore for rejected. So it stop working.
> remove gzip

- README.rst
- doc/source/pycarol/generated/pycarol.functions.misc.rst
- doc/source/pycarol/generated/pycarol.functions.rst
- doc/source/pycarol/pyCarol.rst
- pycarol/connectors.py
- pycarol/functions/__init__.py
- pycarol/functions/misc.py
- pycarol/logger.py
- pycarol/tasks.py
- pycarol/utils/miscellaneous.py
> feature- add handy functions

- pycarol/carol.py
Reuse session from the instance. 
This will reuse the connection instead of creating a new connection each time we call Carol.
> feat: Reuse sessino

- pycarol/bigquery.py
remove type annotation that changes from version to version
> bug: remove type annotation 

- pycarol/bigquery.py
- setup.py
- test/test_sql_bigquery.py
> fixes #551

- setup.py
> fixes #555

- pycarol/carol.py
Get the current user information. 
```
login = Carol( )
user = login.current_user
```
> get current user

- pycarol/carol.py
Allow to switch from org to org and start `Carol()` at org level.
> Carol()  at org level. 

- tutorial/chapters/ch1_introduction/README.md
- tutorial/chapters/ch2_ingestion/README.md
- tutorial/chapters/ch3_datamodel/README.md
- tutorial/chapters/ch4_basic_batchapp/README.md
- tutorial/chapters/ch5_enhanced_batchapp/README.md
- tutorial/chapters/ch6_online_api/README.md
- tutorial/chapters/ch7_user_interface/README.md
- tutorial/chapters/ch8_appendix/README.md
> fixing typos

- pycarol/cds.py
Process using bigquery endpoint.
> Feat: process data using bigquery

- pycarol/carol.py
We need to use a different API to get the current user when in org level.
> add user org level

- pycarol/carolina.py
- pycarol/storage.py
Implement all locking logic on carolina.py.
> feat: add locks to make class manipulation thread safe v3

- pycarol/bigquery.py
BE changed the max value to 24.
> change default value for temp sa

- pycarol/bigquery.py
Added the env Id to the cache name. If the user wants to use pycarol in more than one env. this will not overwrite the local cache.
Not a problem because the CDS cache will still be unique.
> env id to cache

- pycarol/bigquery.py
If the credential is cached in the class, this is returning None.
> Avoid return empty SA

- pycarol/carolina.py
- pycarol/cds.py
Add new params and retry storage on 5xx
> Feat new process big query params

- pycarol/__init__.py
- pycarol/auth/PwdFluig.py
- pycarol/carol.py
- setup.py
Allow use pycarol with fluid identity.
```python
from pycarol import PwdFluig, Carol
carol = Carol(domain, 'teste', auth=PwdFluig(username, password), organization=org)
```
> Fluig identity integration.

- doc/requirements.txt
pycarol requirements were missing from docs.
> adding pycarol requirements to docs

- Makefile
- README.rst
> fixes #dasc-1044

- .github/release-drafter.yml
- set release-drafter workflow labels
> build: set release-drafter workflow labels

- pycarol/staging.py
Jira Issue: https://totvsideia.atlassian.net/browse/DAEN-6364
> Using only intake as send_data option
