totvslabs/pyCarol

- .github/mergeable.yml
The idea is to enable the [mergeability/mergeable](https://github.com/mergeability/mergeable) to ensure a few attributes on pull requests and issues that can help us later to filter and organize better the problems, features and changes.
> feat: added mergeable bot

- pycarol/storage.py
- pycarol/utils/storage_gcpcs.py
The standard value for the google API is 100mb 
`_DEFAULT_CHUNKSIZE = 104857600  # 1024 * 1024 B * 100 = 100 MB` 
I added the option for the user to select this. 
People with slow connections were having timeout issues due to this.
> added chunk_size param to Storage.save and Storage.load

- pycarol/auth/ApiKeyAuth.py
- pycarol/auth/PwdAuth.py
- pycarol/carol.py
- pycarol/organization.py
New feature. This allows the user to change the context of the Carol instance. It means that it is possible to get data from the environment A being in environment B. This only works if the user has access to that environment. 
Context: 
When we are running a carol app, all the credentials come from environment variables. Credentials for that app. An App can have multiples data sources in different environments.
During runtime, i don't have access to the credentials for those data sources. Either I add to the code this credentials, or I get from somewhere. With Carol's organizations, we can do this switch using APIs.
----
I have two implementations for that. 
1. channging the context from B to A. 
```python
carol = Carol('B', 'teste', auth=PwdAuth('email@totvs.com.br', 'pass'),  ) …
```
> Switch context feature. 

- pycarol/carol.py
If the user enters a value for organization it will always be replaced by env variables. 
https://github.com/totvslabs/pyCarol/issues/444
> Fix env. variables overwritten user values. 

- pycarol/carolina.py
- pycarol/storage.py
The sign for the expire was wrong. It would only do this if the token was expired. 
Also, I bypassed this if, because it it was working it would break the second instantiation of any Storage instnace, since it would never start the self.backend. 
The way it was before, it was only using the cache if the expired=True.
> fix problem with expiration data.

- hack/release.sh
Deploy error
```
$ trap 'kill -- $$' INT TERM QUIT; make release
--
  | HEAD is now at aada3dc Merge remote-tracking branch 'origin/master'
  | make[1]: Entering directory '/buildkite/builds/bk-default-agent-97kzb-txnm6-1/totvslabs/pycarol'
  | Packaging pyCarol | 0s
  | Traceback (most recent call last):
  | File "setup.py", line 1, in <module>
  | from distutils.core import setup
  | ModuleNotFoundError: No module named 'distutils.core'
  | Makefile:45: recipe for target 'package' failed
  | make[1]: *** [package] Error 1
  | make[1]: Leaving directory '/buildkite/builds/bk-default-agent-97kzb-txnm6-1/totvslabs/pycarol'
  | Makefile:21: recipe for target 'release' failed
  | make: *** [release] Error 2
```
> Add setup during release.

- pycarol/query.py
Today, using a filter query, it is only possible to download all data from a given query. People are using pycarol in online applications and need to be able to query only a portion of the data to, for instance, to show a table with X results. We need to give the possibility to paginate these results. 
how to use:
```python
login = Carol()
query = Query(login, page_size=10)
query_product_count = {
"mustList": [
{
"mdmFilterType": "TYPE_FILTER",
"mdmValue": "mdmreceiptGolden"
}
]
}
page =  query.query(query_product_count).page(offset=10)
page =  query.page(offset=20)
page =  query.page(offset=30)
```
> add single page return

- pycarol/__init__.py
- pycarol/auth/PwdKeyAuth.py
There are applications that don't don't have access to user/password, or don't want to issue APIkeys when using pycarol. So I created a new Auth method that the user only needs to send a valid password token. 
How to use:
```python
from pycarol import PwdKeyAuth
from pycarol.carol import Carol
from pycarol.apps import Apps
carol = Carol('healthcaresus', 'deepaudit', auth=PwdKeyAuth(access_token='2e1ec4c84j3j43k66b7ec511aaa0ab777'))
app = Apps(carol)
s = app.get_settings(app_name='deepaudit')
```
> new PwdKeyAuth method

- pycarol/__init__.py
- pycarol/data_models/data_models.py
- pycarol/staging.py
Now backend is saving all the staging records in the golden record as metadata. We need to filter this if the user don't want the metadata from a data model. Download all meta can increase a lot of memory consumption. 
I also add a warning to warn the user if a column not in the data model was passed.
> Metadata fetch parquet

- pycarol/auth/PwdKeyAuth.py
- pycarol/carol.py
Remove the initialization of Tenant during the init of Carol instance. This is adding about `300ms`
to initiate the instance. 
@darolt requested to have a "lazy" PwdKeyToken, it means pycarol will not call Carol's API to validate the access token during the instantiation of the class. It will trust in the user access token. 
This is useful for those using pycarol in other APIs and need fast responses. 
```python
carol = Carol(tenant, 'vscode', auth=PwdKeyAuth(access_token=access_token, lazy_login=True), organization=organization)
```
> add support to lazy execute when using the PwdKeyAuth

- README.rst
- pycarol/app/health_check_online.py
- pycarol/apps.py
- pycarol/cds.py
- pycarol/data_models/data_model_view.py
- pycarol/data_models/data_models.py
- pycarol/logger.py
- pycarol/organization.py
- pycarol/query.py
- pycarol/schema_generator.py
- pycarol/staging.py
- pycarol/tenant.py
- pycarol/utils/deprecation_msgs.py
- pycarol/utils/importers.py
- pycarol/utils/miscellaneous.py
- pycarol/utils/storage_gcpcs.py
- setup.py
We have many dependencies in pycarol. But if one only wants to use staging/dm apis I dont need to have Luigi, tornado, flask installed. 
I added more options to install.
e.g., `pip install pycarol[pipeline]` this will install Luigi too. 
`pip install pycarol[dask,pipeline]` this will install dask and Luigi. 
The light version now is much faster to install. 
Question: which version should we send to docker hub? complete?
PS:
I will create a second PR to remove imports in "global" level, that could break this. I am working with desk.
> feat: More install options. 

- pycarol/auth/ApiKeyAuth.py
- pycarol/auth/PwdAuth.py
- pycarol/auth/PwdKeyAuth.py
- pycarol/carol.py
We have the switch context for Envs, now for org too. This allows us from one env/org get credentials for a second org/env that my user has access too. 
Similar to this
https://github.com/totvslabs/pyCarol/pull/443
```python
from pycarol import Carol
carol = Carol('tenantA', 'teste', auth=PwdAuth('rafael.rui@totvs.com.br', 'password'), organization='orgA' )
#inplace change here
carol.switch_environment(env_name='tenantB', org_name='orgB' )
print(carol.get_current())
carol = Carol('tenantA', 'teste', auth=PwdAuth('rafael.rui@totvs.com.br', 'password'), organization='orgA' )
with carol.switch_context('tenantB', org_name='orgB') as carol_orgB:
print(carol_orgB.get_current()) # carol_orgB is the Carol() object logged in `tenantB` and `orgB` 
#back to `tenantA` and `orgA`
```
This works for …
> Switch org

- pycarol/pipeline/task/task.py
Luigi now does not support python2 anymore. We had some imports from Luigi that are not present in this new version.
> Make pycarol compatible with luigi 3.0

- pycarol/organization.py
These to Carol APIs changed behavior. They used to work without authentication, now, if one sends without tokens we dont received the response. When we implemented this in the past, we need to add this special flag for APIs that could be called without token. I added the parameter to send the token, otherwise, this will break some pycarol APIs.
> fix: Organization is not sending Auth information.

- pycarol/carol.py
Switch context was breaking when passing org information being in the same org,
> bug:validate-org-info

- pycarol/logger.py
- pycarol/pipeline/tools/_tools.py
- pycarol/tasks.py
Sometimes carol returns this error when sending logs
```
Exception: ('{"applicationErrorCode":"TEMPORARY_ERROR","errorCode":500,"errorMessage":"An unexpected exception happened while processing your request, please try it again.","possibleResponsibleField":null}', 500)
```
I added a retry with backoff for these codes `500, 502, 503,  504, 524` 
I also removed some old stuff from luigi in the logger.
> feat: retry when logs data to carol. 

- .buildkite/pipeline.sh
There was a change on Buildkite configuration where the `default` queue was removed, defaulting to `general` now.
> fix: buildkite queue name

- pycarol/carol.py
It is not possible having only `CAROLUSER` and `CAROLPWD` in env variables and create the `Carol()` instance. I isolate the entries to allow this.
> feat: allow to creat Carol with env variables only.

- pycarol/data_models/data_models.py
If no payload is sent, and the method is not set, it infers the type. In this call is was assuming the wrong method.
> fix: pycarol were assuming a GET method. 

- pycarol/__init__.py
@poffo noticed that there was one missing column in fetch parquet for stagings.
> fix: Missing metadata column in fetch from staging

- pycarol/staging.py
pycarol was overwriting the step_size when sending data using carol_sync, even if the step_size < max carol step size. 
https://github.com/totvslabs/pyCarol/issues/493
> bug: step_size when using carol_sync

- setup.py
There is a problem in google core apis when using 1.31 version [link](https://github.com/googleapis/python-cloud-core/issues/23). [link](https://github.com/googleapis/google-cloud-python/issues/10471)
Pump the version to 1.41 fixes this problem. It seems using 1.30 works, but 1.31, 1.4 dont.
> Google storage

- pycarol/tasks.py
We can have 500 errors when carol is unstable. This will retry when receiving a 500 error.
> feat: retry policy for tasks.

- pycarol/utils/async_helpers.py
The async send was not locking when printing. So the prints were overlapping.
> bug- Print when sending async.

- pycarol/carol.py
Today we need to either pass the AUTH to Carol constructor or use env. variables. I added the username/password and api_key to the constructor to make the life of users easy.
> add user/password ans api_key to Carol

- pycarol/__init__.py
- pycarol/carol.py
- pycarol/carol_api.py
- pycarol/query.py
Added some modules in a single class. How to use
```python
from pycarol import CarolAPI
carol = CarolAPI()
carol.storage.save(name='myfile.csv', obj='/local/file/.csv',  format='file')
#fetch data from staging
df = carol.staging.fetch_parquet(staging_name=staging,  
connector_name=connector_name,)
carol._all_modules
```
If one wants to use a module not in "carol._all_modules" it is possible to add new modules using:
```python
from pycarol import CarolAPI
carol = CarolAPI()
carol.add_module('new_module', 'ANewModule')
```
Note that this module will receita pycarol.Carol as the first argument. If the module require extra arguments,
use:
```python
from pycarol import CarolAPI
carol = CarolAPI()
carol.add_module('new_module', 'ANewModule', allow_args=True)
carol.new_module(extra_arg, …
```
> feat: encapsulate some modules in a single class

- pycarol/carol_api.py
@gzamboni 
Playing with eh context I realized that I can extend the Carol class to use this feature. 
We can then just do
```python
from pycarol import CarolAPI as Carol
```
and it would be compatible. I think it would be possible to add directly to Carol's class, but it could have some cyclic dependences in some modules. It is safer to isolate this.
> feat: improve CarolAPI

- pycarol/bigquery.py
- pycarol/sql.py
fixing https://github.com/totvslabs/pyCarol/issues/563 and
https://github.com/totvslabs/pyCarol/issues/564
for https://github.com/totvslabs/pyCarol/issues/564 you were using a sandbox, today carol does not provide an API to pycarol to solve the dataset ID, so I added a option to overwrite the default production dataset_id
> bug: returning dataframe when using bq and dataset if

- pycarol/bigquery.py
- pycarol/carol.py
1. Allow users to create SA.
2. Cache system to avoid recreating  SAs. 
PS: I did not remove the old query process. We need to see if people are using it. I removed all the query preparation. First, because in the new big query the connector_name is the default prefix. Second, if anything changes in these definitions we need to change in pycarol. Let's wait for this feature to be more mature then we can add this.
Usage:
```python
from pycarol import Carol
from pycarol.bigquery import BQ
bq = BQ(Carol())
query = 'select * from invoice limit 10'	
df = bq.query(query, return_dataframe=True)
```
No need to request a SA to use in query. pycarol will handle it.
But, if one wants
```python
from pycarol import Carol
from pycarol.bigquery import BQ
bq = BQ(Carol())
service_account = …
```
> big query query and SA generation

- pycarol/bigquery.py
It can happen that the `self.storage` is not defined when this is called. 
Also added the check to create the temp folder with it does not exists.
> bug when storage does not exist

- pycarol/bigquery.py
There is an error when caching the storage that happens sometimes we cannot find the reason. It seems something in google/carol.
For now, I added a try-catch to avoid breaking the BQ.
> try catch storage

- pycarol/schema_generator.py
dasc-1167
Managed to reproduce the error with pycarol 3.8 and numpy 1.21.6.
After fix tested with pycarol 3.7, 3.8 and 3.11. numpy 1.21.6, 1.24.3 and 1.25.2.
> fix: adding retrocompatibility

- pycarol/carol.py
- setup.py
The first fix forced urllib3 version which may impact developers that do not set their version for pycarol. This new solution allow for all versions without fixing any versions.
https://totvslabs.atlassian.net/browse/DASC-1272
> fix: rolling back to allow for all urllib3 versions

- pycarol/bigquery.py
There was a fix in the BQStorage API. We were setting the maximum number of streams to 4 and were using only 1. Setting maximum number of streams to 1 to fix this bug. In the future we can expose this parameter.
https://totvslabs.atlassian.net/browse/DASC-1191
> fix: missing streams in BQStorage

- pycarol/bigquery.py
- test/test_bigquery.py
The PR adds labels to the BigQuery.JobConfig in order to help us understand the job's performances better and enable new segmentation strategies for the Carol Apps.
https://totvslabs.atlassian.net/browse/DASC-1208?atlOrigin=eyJpIjoiOWZhZTc4ZDViYmUxNDhlNmIyNWVkOGY4YWRmNTc0ZjciLCJwIjoiaiJ9
- ~Although the behaviour of the `BQ.query` function has not changed in a production test. I was unable to verify that the labels were added to the BigQuery job because I don't have access to the tables. Maybe there is another way to check this in production, but I couldn't find it.~
- ~I added some doubts in the code to check if my decision was correct for the respective labels.~
> Dasc 1208/add labels to bq job config

- README.rst
- pycarol/cds.py
- pycarol/data_models/data_models.py
- pycarol/functions/misc.py
- pycarol/staging.py
- pycarol/utils/miscellaneous.py
Jira Issue: https://totvsideia.atlassian.net/browse/DAEN-5276 
This PR intends to deprecate CDS reading by using deprecated decorator. In a future PR, the capability to read data from CDS will be fully removed from pycarol.
https://totvsideia.atlassian.net/browse/DAEN-5276
> DAEN-5276 - Deprecate CDS reading

- pycarol/bigquery.py
- setup.py
Jira Issue: https://totvsideia.atlassian.net/browse/DAEN-6225 
Jira issue: https://totvsideia.atlassian.net/browse/DAEN-6225
- Added pandas and numpy as minimum requirements. 
Since pycarol is most used for data manipulation using BigQuery and pandas nowadays, pandas and numpy are being treated now as minimum requirements starting from this version. This avoids the necessity of importing pandas alongside with pycarol and avoids errors because pandas was not imported.
- Added pip-system-certs as minimum requirements. 
This is to prevent SSL errors on DOS based terminals (e.g. powershell or command prompt).
- Added service account checking inside query method.
Recently we were facing JWT errors when using BigQuery interfaces with Service Accounts that have expired while the BQ object was …
> Requirements review and BigQuery ServiceAccount checking improvements.
